"""Add display_summary as column on Podcast

Revision ID: 05343b6f364f
Revises: 5ee3b7552ada
Create Date: 2017-06-02 11:41:24.932254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05343b6f364f'
down_revision = '5ee3b7552ada'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('podcasts', sa.Column('display_summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('podcasts', 'display_summary')
    # ### end Alembic commands ###
