"""add itunes_id and truncated summary as columns on podcast

Revision ID: 08a422fe2e69
Revises: 2af0d05ef87f
Create Date: 2017-06-01 16:21:39.152492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08a422fe2e69'
down_revision = '2af0d05ef87f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('podcasts', sa.Column('itunes_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('podcasts', 'itunes_id')
    # ### end Alembic commands ###
