"""Add podcasts as column on Users and add userPodcasts through table

Revision ID: 2af0d05ef87f
Revises: c31e32e2350a
Create Date: 2017-06-01 15:36:13.171055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2af0d05ef87f'
down_revision = 'c31e32e2350a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_podcasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('podcast_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['podcast_id'], ['podcasts.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('users', 'playlist_titles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('playlist_titles', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_table('user_podcasts')
    # ### end Alembic commands ###
