"""Add playlist_titles as a column on Users

Revision ID: 5edb78d548ec
Revises: a0ccd626bf75
Create Date: 2017-05-31 16:22:20.421058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5edb78d548ec'
down_revision = 'a0ccd626bf75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('playlist_titles', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'playlist_titles')
    # ### end Alembic commands ###
