"""create preferences table and user-preferences through table

Revision ID: 98448477df9f
Revises: 79570f404d85
Create Date: 2017-05-28 22:47:06.541770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98448477df9f'
down_revision = '79570f404d85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('preference_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['preference_id'], ['preferences.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('users', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('location', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_table('user_preferences')
    op.drop_table('preferences')
    # ### end Alembic commands ###
