"""Add playlist as column on User

Revision ID: a0ccd626bf75
Revises: e0c7554d9295
Create Date: 2017-05-31 15:34:28.261321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0ccd626bf75'
down_revision = 'e0c7554d9295'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('playlist', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'playlist')
    # ### end Alembic commands ###
