"""remove 'firstname and lastname' columns from user table

Revision ID: e0c7554d9295
Revises: 98448477df9f
Create Date: 2017-05-29 00:49:30.625887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0c7554d9295'
down_revision = '98448477df9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'last_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('first_name', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
